const MockData = [
  {
    first_name: "John",
    last_name: "Doe",
    job_company_name: "Google",
    job_title: "Software Engineer",
    credit_count: 850,
    confidence_level: 95,
  },
  {
    first_name: "Emily",
    last_name: "Smith",
    job_company_name: "Apple",
    job_title: "UX Designer",
    credit_count: 820,
    confidence_level: 93,
  },
  {
    first_name: "Michael",
    last_name: "Johnson",
    job_company_name: "Microsoft",
    job_title: "Product Manager",
    credit_count: 880,
    confidence_level: 96,
  },
  {
    first_name: "Sarah",
    last_name: "Brown",
    job_company_name: "Amazon",
    job_title: "Data Scientist",
    credit_count: 830,
    confidence_level: 94,
  },
  {
    first_name: "Daniel",
    last_name: "Lee",
    job_company_name: "Facebook",
    job_title: "Marketing Manager",
    credit_count: 860,
    confidence_level: 97,
  },
  {
    first_name: "Matthew",
    last_name: "Taylor",
    job_company_name: "Google",
    job_title: "Product Manager",
    credit_count: 860,
    confidence_level: 94,
  },
  {
    first_name: "Olivia",
    last_name: "Wilson",
    job_company_name: "Google",
    job_title: "Software Engineer",
    credit_count: 840,
    confidence_level: 93,
  },
  {
    first_name: "Sophia",
    last_name: "Lopez",
    job_company_name: "Google",
    job_title: "UX Designer",
    credit_count: 830,
    confidence_level: 92,
  },
  {
    first_name: "Ethan",
    last_name: "Gonzalez",
    job_company_name: "Google",
    job_title: "Data Scientist",
    credit_count: 870,
    confidence_level: 95,
  },
  {
    first_name: "Emma",
    last_name: "Anderson",
    job_company_name: "Apple",
    job_title: "Marketing Manager",
    credit_count: 850,
    confidence_level: 94,
  },
  {
    first_name: "Lucas",
    last_name: "Martinez",
    job_company_name: "Apple",
    job_title: "Software Developer",
    credit_count: 820,
    confidence_level: 91,
  },
  {
    first_name: "Isabella",
    last_name: "Hernandez",
    job_company_name: "Apple",
    job_title: "UX Designer",
    credit_count: 830,
    confidence_level: 92,
  },
  {
    first_name: "Alexander",
    last_name: "Young",
    job_company_name: "Apple",
    job_title: "Data Analyst",
    credit_count: 840,
    confidence_level: 93,
  },
  {
    first_name: "Mia",
    last_name: "Perez",
    job_company_name: "Microsoft",
    job_title: "Product Manager",
    credit_count: 870,
    confidence_level: 95,
  },
  {
    first_name: "Benjamin",
    last_name: "Turner",
    job_company_name: "Microsoft",
    job_title: "Software Engineer",
    credit_count: 850,
    confidence_level: 94,
  },
  {
    first_name: "Charlotte",
    last_name: "Thomas",
    job_company_name: "Microsoft",
    job_title: "UX Designer",
    credit_count: 830,
    confidence_level: 93,
  },
  {
    first_name: "Gabriel",
    last_name: "Harris",
    job_company_name: "Microsoft",
    job_title: "Data Scientist",
    credit_count: 880,
    confidence_level: 96,
  },
  {
    first_name: "Harper",
    last_name: "King",
    job_company_name: "Amazon",
    job_title: "Marketing Manager",
    credit_count: 840,
    confidence_level: 94,
  },
  {
    first_name: "Leo",
    last_name: "White",
    job_company_name: "Amazon",
    job_title: "Software Developer",
    credit_count: 820,
    confidence_level: 91,
  },
  {
    first_name: "Evelyn",
    last_name: "Scott",
    job_company_name: "Amazon",
    job_title: "UX Designer",
    credit_count: 830,
    confidence_level: 92,
  },
  {
    first_name: "Jackson",
    last_name: "Taylor",
    job_company_name: "Amazon",
    job_title: "Data Analyst",
    credit_count: 850,
    confidence_level: 93,
  },
];

export default MockData;
